[project]
name = "smart-factory"
version = "0.1.0"
description = "Laboratory - Python Object-Oriented Programming - Industrial Use Case"
readme = "README.md"
authors = [
    { name = "Marco Picone" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
smart-factory = "smart_factory.main:main"

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"
